import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LNav from "../components/loged/LNav";
import Side from "../newCompmnents/Sdie";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <LNav /> */}
      <div className="flex bg-white min-h-screen overflow-y-hidden">
        <Side />
        <div className="bg-[#F2F1EF] rounded-l-3xl w-full p-10 shadow-inner ">
          {children}
        </div>
      </div>
    </>
  );
}
